install_data(
  'io.github.agustingv.noteme.desktop',
  install_dir: get_option('datadir') / 'applications',
)

install_data(
  'io.github.agustingv.noteme.metainfo.xml',
  install_dir: get_option('datadir') / 'metainfo',
)

install_data(
  'icons/hicolor/scalable/apps/io.github.agustingv.noteme.svg',
  install_dir: get_option('datadir') / 'icons' / 'hicolor' / 'scalable' / 'apps',
)
